apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.app.name }}
spec:
  replicas: {{ .Values.global.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.app.selector.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.app.selector.matchLabels.app }}
    spec:
      containers:
        - name: {{ index .Values.global.app.containers 0 "name" }}
          image: {{ .Values.global.app.image.repository }}:{{ .Values.global.app.image.tag }}
          ports:
            - containerPort: {{ .Values.global.app.containerPort }}
