apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - {{ index .Values.pvc.accessModes 0 }}
  resources:
    requests:
      storage: {{ .Values.postgres.volumeSize }}
  storageClassName: {{ .Values.pvc.storageClassName }}
