apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.service_app.name }}
spec:
  selector:
    app: {{ .Values.global.app.selector.matchLabels.app }}
  ports:
    - protocol: {{ index .Values.global.service_app.selector.ports 0 "protocol" }}
      port: {{ index .Values.global.service_app.selector.ports 0 "port" }}
      nodePort: {{ index .Values.global.service_app.selector.ports 0 "nodePort" }}
  type: {{ .Values.global.service_app.selector.type }}
