apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: {{ index .Values.service_postgres.ports 0 "protocol" }}
      port: {{ index .Values.service_postgres.ports 0 "port" }}